"""
T2 Iris -- SOAP payments client.

Uses the getTransactionByUpdateDate method on Digital Iris TransactionDataService.

SOAP endpoint:
    WSDL: {T2_IRIS_BASE_URL}/TransactionDataService?wsdl
    Default: https://api.digitalpaytech.com/services/TransactionDataService?wsdl

Config (.env):
    T2_IRIS_BASE_URL  -- base URL for Digital Iris services
                         (default: https://api.digitalpaytech.com/services)
    T2_IRIS_TOKEN     -- token generated by Iris for this endpoint

Key constraint -- 24-hour window:
    getTransactionByUpdateDate cannot span more than 24 hours per call.
    To fetch a full month we loop day by day in UTC (30-31 calls).
    Timestamps are Zulu (UTC), so we query one UTC day at a time and accept
    that a handful of late-PDT transactions on the last day of the month
    may fall into the next UTC day -- negligible for a 6-visit threshold.

Filtering:
    - plateNumber must be non-empty
    - chargedAmount > 0  (excludes test transactions which charge nothing)

Stub mode (USE_STUBS_PAYMENTS=true):
    Loads plates from test-data/*Payment*.csv.
    The CSV format uses Excel formula quoting (="SK041H") so normalise_payments_plate
    is used for the file path only. Live API returns plain strings.
"""

from __future__ import annotations

import asyncio
import calendar
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path

import pandas as pd

from app.config import settings
from app.core.normalise import normalise_payments_plate, normalise_reads_plate
from app.integrations.base import Payment, PaymentsClient

logger = logging.getLogger(__name__)

# Lazy-loaded zeep client -- initialised on first live call, not at import time.
_iris_client = None


def _get_iris_client():
    """
    Return (and cache) a zeep SOAP client for TransactionDataService.

    zeep fetches and parses the WSDL on first call. If the WSDL is
    unreachable (e.g. running off-campus without VPN) this will raise
    a descriptive error rather than a cryptic import failure.
    """
    global _iris_client
    if _iris_client is None:
        try:
            from zeep import Client  # deferred import -- avoids startup cost in stub mode
        except ImportError as exc:
            raise RuntimeError(
                "zeep is required for the T2 Iris live client. "
                "Run: pip install zeep"
            ) from exc

        wsdl = f"{settings.t2_iris_base_url.rstrip('/')}/TransactionDataService?wsdl"
        logger.info("Initialising T2 Iris SOAP client from WSDL: %s", wsdl)
        _iris_client = Client(wsdl)

    return _iris_client


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------

class T2IrisClient(PaymentsClient):

    async def fetch_payments(self, year: int, month: int) -> list[Payment]:
        if settings.use_stubs_payments:
            return _load_payments_from_file(year, month)
        return await _fetch_payments_live(year, month)


# ---------------------------------------------------------------------------
# Live -- day-by-day SOAP calls
# ---------------------------------------------------------------------------

async def _fetch_payments_live(year: int, month: int) -> list[Payment]:
    """
    Fetch all payment plates for the given month via TransactionDataService.

    Calls getTransactionByUpdateDate once per calendar day (UTC) to respect
    the 24-hour window limit. Collects unique plates across all days.
    """
    if not settings.t2_iris_token:
        raise RuntimeError(
            "T2_IRIS_TOKEN is not set in .env. "
            "Add the token generated by Digital Iris for the TransactionDataService endpoint."
        )

    # Generate (from, to) pairs: midnight-to-midnight UTC for each day of the month
    num_days = calendar.monthrange(year, month)[1]
    windows: list[tuple[datetime, datetime]] = []
    for day in range(1, num_days + 1):
        from_dt = datetime(year, month, day, 0, 0, 0, tzinfo=timezone.utc)
        to_dt = from_dt + timedelta(hours=23, minutes=59, seconds=59)
        windows.append((from_dt, to_dt))

    plates: set[str] = set()
    total_rows = 0

    for from_dt, to_dt in windows:
        rows = await asyncio.to_thread(_call_get_transactions, from_dt, to_dt)
        total_rows += len(rows)
        for row in rows:
            plate = _extract_plate(row)
            if plate:
                plates.add(plate)

    logger.info(
        "_fetch_payments_live(%d-%02d): %d unique plates from %d total rows across %d days",
        year, month, len(plates), total_rows, num_days,
    )
    return [Payment(plate=p) for p in plates]


def _call_get_transactions(from_dt: datetime, to_dt: datetime) -> list:
    """
    Synchronous zeep call -- run via asyncio.to_thread() to avoid blocking the event loop.

    Returns the raw zeep response list (or empty list on error).
    The response shape depends on the WSDL; zeep wraps it as a list-like
    object when the method returns an array of complex types.
    """
    client = _get_iris_client()
    # The API expects bare Zulu format (yyyy-mm-ddThh:mm:ss) with no timezone offset suffix.
    # Passing a timezone-aware datetime makes zeep serialize it as +00:00 which the server rejects.
    # Strip tzinfo so zeep emits the plain format the API requires.
    result = client.service.getTransactionByUpdateDate(
        token=settings.t2_iris_token,
        updateDateFrom=from_dt.replace(tzinfo=None),
        updateDateTo=to_dt.replace(tzinfo=None),
    )

    if result is None:
        return []

    # zeep returns either a list or a single object depending on WSDL definition
    if isinstance(result, list):
        return result

    # Some WSDL definitions wrap results in a container object.
    # Try common attribute names used by zeep for array responses.
    for attr in ("TransactionData", "item", "return", "result"):
        inner = getattr(result, attr, None)
        if inner is not None:
            return list(inner) if hasattr(inner, "__iter__") else [inner]

    return list(result) if hasattr(result, "__iter__") else [result]


def _extract_plate(row) -> str:
    """
    Extract and normalise a plate from a zeep TransactionData object.

    Plates from the live API are plain strings (not Excel-quoted), so we
    use normalise_reads_plate (uppercase + trim only -- no ="" stripping).
    Rows with no plate or zero charge are discarded.
    """
    # zeep returns objects with attribute access; fall back to dict-style for safety
    plate_raw = getattr(row, "plateNumber", None)
    if plate_raw is None and hasattr(row, "get"):
        plate_raw = row.get("plateNumber")

    charged = getattr(row, "chargedAmount", None)
    if charged is None and hasattr(row, "get"):
        charged = row.get("chargedAmount")

    if not plate_raw:
        return ""

    # Exclude test / zero-charge transactions
    try:
        if float(charged or 0) <= 0:
            return ""
    except (TypeError, ValueError):
        pass  # If we cannot parse the amount, include the plate (safer than excluding)

    return normalise_reads_plate(str(plate_raw))


# ---------------------------------------------------------------------------
# Stub loader -- CSV file path (Excel formula-quoted plates)
# ---------------------------------------------------------------------------

def _load_payments_from_file(year: int, month: int) -> list[Payment]:
    stub_dir = Path(settings.stub_data_dir)
    candidates = (
        sorted(stub_dir.glob("*Payment*.csv"))
        + sorted(stub_dir.glob("*payment*.csv"))
    )

    if not candidates:
        return []

    path = candidates[0]
    df = pd.read_csv(path, dtype=str)
    df.columns = df.columns.str.strip()

    plate_col = next(
        (c for c in df.columns if "license plate" in c.lower() or "licence plate" in c.lower()),
        None,
    )
    if not plate_col:
        return []

    # CSV file uses Excel formula quoting (="SK041H") -- use the file-specific normaliser
    plates = df[plate_col].apply(normalise_payments_plate)
    plates = plates[plates != ""].drop_duplicates()
    return [Payment(plate=p) for p in plates]
