"""
Tests for the 2026-06 hardening pass:
- Genetec reads parser: both export formats, UTC-bug regression, month filter
- T2 Iris live-row plate extraction edge cases
- normalise_iris_plate typed-input cleanup
- Full upload -> analyze -> draw smoke test through the FastAPI app
"""

from datetime import datetime
from types import SimpleNamespace

import pytest
from openpyxl import Workbook

from app.core.normalise import normalise_iris_plate, normalise_payments_plate
from app.integrations.genetec import ReadsFileError, _parse_reads_file, _reads_for_month, inspect_reads_file
from app.integrations.t2_iris import _extract_plate

EXCEL_EPOCH = datetime(1899, 12, 30)


def _serial(dt: datetime) -> float:
    return (dt - EXCEL_EPOCH).total_seconds() / 86400


def _write_new_format(path, rows):
    """Genetec Security Desk export: 6 junk rows, header on row 7, serial timestamps."""
    wb = Workbook()
    ws = wb.active
    for _ in range(6):
        ws.append(["Report generated by Security Desk", None])
    ws.append(["Plate read", "Read timestamp"])
    for plate, dt in rows:
        ws.append([plate, _serial(dt)])
    wb.save(path)


def _write_old_format(path, rows):
    """Cloudrunner export: 1 junk row, header on row 2, string timestamps."""
    wb = Workbook()
    ws = wb.active
    ws.append(["Cloudrunner report", None])
    ws.append(["Plate number", "Local time (PDT)"])
    for plate, dt in rows:
        ws.append([plate, dt.strftime("%m/%d/%Y, %I:%M:%S %p")])
    wb.save(path)


# ---------------------------------------------------------------------------
# Genetec parser
# ---------------------------------------------------------------------------

class TestReadsParser:
    def test_new_format_parses(self, tmp_path):
        f = tmp_path / "reads.xlsx"
        _write_new_format(f, [
            ("SK041H", datetime(2026, 4, 15, 9, 0, 0)),
            ("AB123C", datetime(2026, 4, 15, 10, 30, 0)),
        ])
        df = _parse_reads_file(f)
        assert sorted(df["plate"]) == ["AB123C", "SK041H"]

    def test_old_format_parses(self, tmp_path):
        f = tmp_path / "reads.xlsx"
        _write_old_format(f, [("SK041H", datetime(2026, 4, 15, 9, 0, 0))])
        df = _parse_reads_file(f)
        assert list(df["plate"]) == ["SK041H"]

    def test_utc_bug_regression_late_evening_read_keeps_local_date(self, tmp_path):
        """A read at 11:56 PM must stay on the same calendar date (the old
        toISOString bug shifted it to the next day)."""
        f = tmp_path / "reads.xlsx"
        late = datetime(2026, 4, 30, 23, 56, 9)
        _write_new_format(f, [("SK041H", late)])
        df = _parse_reads_file(f)
        assert df["ts"].iloc[0].date() == late.date()
        assert df["ts"].iloc[0].hour == 23

    def test_month_filter_rejects_wrong_month(self, tmp_path):
        f = tmp_path / "reads.xlsx"
        _write_new_format(f, [("SK041H", datetime(2026, 4, 15, 9, 0, 0))])
        df = _parse_reads_file(f)
        with pytest.raises(ReadsFileError, match="2026-05"):
            _reads_for_month(df, 2026, 5, source="reads.xlsx")

    def test_month_filter_keeps_right_month_only(self, tmp_path):
        f = tmp_path / "reads.xlsx"
        _write_new_format(f, [
            ("SK041H", datetime(2026, 4, 15, 9, 0, 0)),
            ("ZZ999Z", datetime(2026, 5, 1, 0, 5, 0)),  # spillover row
        ])
        df = _parse_reads_file(f)
        reads = _reads_for_month(df, 2026, 4, source="reads.xlsx")
        assert [r.plate for r in reads] == ["SK041H"]

    def test_not_a_reads_file(self, tmp_path):
        f = tmp_path / "junk.xlsx"
        wb = Workbook()
        ws = wb.active
        ws.append(["Totally", "Unrelated"])
        ws.append(["a", "b"])
        wb.save(f)
        with pytest.raises(ReadsFileError, match="does not look like"):
            _parse_reads_file(f)

    def test_inspect_reports_coverage(self, tmp_path):
        f = tmp_path / "reads.xlsx"
        _write_new_format(f, [
            ("SK041H", datetime(2026, 4, 1, 9, 0, 0)),
            ("SK041H", datetime(2026, 4, 30, 9, 0, 0)),
        ])
        info = inspect_reads_file(f)
        assert info.total_rows == 2
        assert info.date_min == "2026-04-01"
        assert info.date_max == "2026-04-30"
        assert info.months_covered == ["2026-04"]


# ---------------------------------------------------------------------------
# Iris row extraction
# ---------------------------------------------------------------------------

class TestIrisExtraction:
    def test_normal_row(self):
        row = SimpleNamespace(plateNumber="sk041h", chargedAmount=4.5,
                              totalCardAmount=4.5, totalCashAmount=0)
        assert _extract_plate(row) == "SK041H"

    def test_typed_input_noise_removed(self):
        row = SimpleNamespace(plateNumber=" ab 123-c ", chargedAmount=2.0,
                              totalCardAmount=0, totalCashAmount=0)
        assert _extract_plate(row) == "AB123C"

    def test_sk_prefix_never_stripped(self):
        """SK041H bug regression: SK looks like Saskatchewan but is the plate."""
        row = SimpleNamespace(plateNumber="SK041H", chargedAmount=1.0,
                              totalCardAmount=0, totalCashAmount=0)
        assert _extract_plate(row) == "SK041H"

    def test_no_plate_discarded(self):
        row = SimpleNamespace(plateNumber=None, chargedAmount=4.5,
                              totalCardAmount=0, totalCashAmount=0)
        assert _extract_plate(row) == ""

    def test_zero_value_transaction_kept(self):
        """$0 transactions (coupons / free periods) ARE payments -- the
        report includes them; filtering them removed 446 April plates."""
        row = SimpleNamespace(plateNumber="AB123C", chargedAmount=0,
                              totalCardAmount=0, totalCashAmount=0)
        assert _extract_plate(row) == "AB123C"

    def test_cash_only_transaction_kept(self):
        row = SimpleNamespace(plateNumber="AB123C", chargedAmount=0,
                              totalCardAmount=None, totalCashAmount=3.0)
        assert _extract_plate(row) == "AB123C"

    def test_missing_amount_fields_kept(self):
        row = SimpleNamespace(plateNumber="AB123C", chargedAmount=None,
                              totalCardAmount=None, totalCashAmount=None)
        assert _extract_plate(row) == "AB123C"


class TestIrisUtcWindows:
    """The campus-local month must map to exact UTC day-windows.
    April 2026 in America/Vancouver is PDT (UTC-7)."""

    def test_april_2026(self):
        from app.integrations.t2_iris import _month_utc_windows
        windows = _month_utc_windows(2026, 4)
        # Apr 1 00:00 PDT = Apr 1 07:00 UTC; Apr 30 23:59:59 PDT = May 1 06:59:59 UTC
        assert windows[0][0] == datetime(2026, 4, 1, 7, 0, 0)
        assert windows[-1][1] == datetime(2026, 5, 1, 6, 59, 59)
        # every window stays within one UTC calendar day
        for start, end in windows:
            assert start.date() == end.date()
            assert start <= end
        # contiguous coverage: 30 full days needs 31 windows (two partials)
        assert len(windows) == 31


class TestIrisNormaliser:
    def test_cases(self):
        assert normalise_iris_plate("ab 123c") == "AB123C"
        assert normalise_iris_plate("AB-123C") == "AB123C"
        assert normalise_iris_plate("  sk041h ") == "SK041H"
        assert normalise_iris_plate(None) == ""
        assert normalise_iris_plate("") == ""

    def test_csv_normaliser_matches_live(self):
        assert normalise_payments_plate('="SK041H"') == "SK041H"
        assert normalise_payments_plate('="AB 123C"') == "AB123C"


# ---------------------------------------------------------------------------
# End-to-end smoke test: upload -> analyze -> draw
# ---------------------------------------------------------------------------

@pytest.fixture
def client(tmp_path, monkeypatch):
    from fastapi.testclient import TestClient
    from app.config import settings
    from app.store import csv_store, reads_db
    from app.main import app

    monkeypatch.setattr(reads_db, "_db_path", lambda: tmp_path / "reads.db")

    stub_dir = tmp_path / "stub"
    uploads_dir = tmp_path / "uploads"
    data_dir = tmp_path / "data"
    stub_dir.mkdir(), uploads_dir.mkdir(), data_dir.mkdir()

    # Payments CSV (Excel formula-quoted plates)
    (stub_dir / "April_Payments.csv").write_text(
        'License Plate,Amount\r\n"=""SK041H""",4.50\r\n"=""AB123C""",2.00\r\n'
    )
    # Permit holders file
    (stub_dir / "Active_Permits.txt").write_text(
        "Distinct of ENT_UID,EMAIL_ADDRESS,SERIES_PREFIX,PERMIT_NUMBER,LICENSE_PLATES\n"
        '1001,holder@ubc.ca,STAFF,P-1,XY987Z\n'
        '1002,,STAFF,P-2,NOMAIL1\n'
    )

    monkeypatch.setattr(settings, "stub_data_dir", str(stub_dir))
    monkeypatch.setattr(settings, "uploads_dir", str(uploads_dir))
    monkeypatch.setattr(settings, "use_stubs", True)
    monkeypatch.setattr(settings, "use_stubs_payments", True)
    monkeypatch.setattr(settings, "smtp_username", "")
    monkeypatch.setattr(csv_store, "_data_dir", lambda: data_dir)

    return TestClient(app)


def _reads_xlsx_bytes(tmp_path) -> bytes:
    f = tmp_path / "April_export.xlsx"
    rows = []
    # SK041H: 3 qualifying days (>= 1h span each)
    for day in (10, 11, 12):
        rows.append(("SK041H", datetime(2026, 4, day, 9, 0, 0)))
        rows.append(("SK041H", datetime(2026, 4, day, 11, 0, 0)))
    # AB123C: visits but spans < 1h -> not qualifying
    for day in (10, 11, 12):
        rows.append(("AB123C", datetime(2026, 4, day, 9, 0, 0)))
        rows.append(("AB123C", datetime(2026, 4, day, 9, 20, 0)))
    _write_new_format(f, rows)
    return f.read_bytes()


class TestEndToEnd:
    def test_full_flow(self, client, tmp_path):
        # No reads uploaded yet -> analyze fails with a clear message
        r = client.post("/api/analyze", json={"year": 2026, "month": 4, "min_visits": 3, "actor": "test"})
        assert r.status_code == 422
        assert "No plate reads available" in r.json()["detail"]

        # Upload the reads export
        r = client.post(
            "/api/upload/reads",
            files={"file": ("April_export.xlsx", _reads_xlsx_bytes(tmp_path),
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")},
        )
        assert r.status_code == 200, r.text
        assert r.json()["months_covered"] == ["2026-04"]

        # Analyze: SK041H qualifies via payment track; permit holders via permit track
        r = client.post("/api/analyze", json={"year": 2026, "month": 4, "min_visits": 3, "actor": "test"})
        assert r.status_code == 200, r.text
        body = r.json()
        plates = {q["plate"]: q["track"] for q in body["qualifiers"]}
        assert plates["SK041H"] == "payment"
        assert plates["XY987Z"] == "permit"
        assert plates["NOMAIL1"] == "permit"
        assert "AB123C" not in plates  # span too short
        assert body["summary"]["final"] == 3

        # Wrong month -> friendly error
        r = client.post("/api/analyze", json={"year": 2026, "month": 5, "min_visits": 3, "actor": "test"})
        assert r.status_code == 422
        assert "2026-05" in r.json()["detail"]

        # Draw without a name -> rejected
        r = client.post("/api/draw", json={"year": 2026, "month": 4, "num_winners": 1,
                                           "min_visits": 3, "actor": "  "})
        assert r.status_code == 400

        # Draw
        r = client.post("/api/draw", json={"year": 2026, "month": 4, "num_winners": 1,
                                           "min_visits": 3, "actor": "test"})
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["pool_size"] == 3
        assert len(d["winners"]) == 1
        assert d["is_redraw"] is False

        # Redraw without manager code -> blocked
        r = client.post("/api/draw", json={"year": 2026, "month": 4, "num_winners": 1,
                                           "min_visits": 3, "actor": "test"})
        assert r.status_code == 403

        # Redraw with manager code -> allowed
        from app.config import settings
        r = client.post("/api/draw", json={"year": 2026, "month": 4, "num_winners": 1,
                                           "min_visits": 3, "actor": "test",
                                           "manager_code": settings.manager_code})
        assert r.status_code == 200
        assert r.json()["is_redraw"] is True

        # History shows exactly one record for the month
        r = client.get("/api/history")
        assert r.status_code == 200
        months = [row["month"] for row in r.json()]
        assert months.count("2026-04") == 1
