from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Genetec (plate reads) -- live client not yet implemented; use stub
    genetec_base_url: str = ""
    genetec_username: str = ""
    genetec_password: str = ""

    # T2 Iris (payments) -- SOAP TransactionDataService
    t2_iris_base_url: str = "https://api.digitalpaytech.com/services"
    t2_iris_token: str = ""          # Token generated by Iris for this endpoint

    # T2 Flex -- SOAP web services (T2_Flex_Misc.asmx / ExecuteQuery method)
    t2_flex_ws_url: str = ""
    t2_flex_username: str = ""
    t2_flex_password: str = ""
    t2_flex_query_permits_uid: int = 0
    t2_flex_query_citations_uid: int = 0
    t2_flex_verify_ssl: bool = True
    t2_flex_timeout: float = 60.0

    # Email (UBC Exchange/SMTP)
    smtp_host: str = "smtp.mail.ubc.ca"
    smtp_port: int = 587
    smtp_username: str = ""
    smtp_password: str = ""
    email_from: str = "parking.perks@ubc.ca"
    email_from_name: str = "UBC Parking Services"

    # Application
    manager_code: str = "UBCO-PERKS-2025"
    min_visits: int = 10
    min_hours: float = 1.0
    num_winners: int = 1
    campus_timezone: str = "America/Vancouver"

    # Scheduler -- monthly draw runs at draw_hour:draw_minute on draw_day_of_month
    draw_day_of_month: int = 1
    draw_hour: int = 9
    draw_minute: int = 0

    # Stub flags (set to false individually as live APIs become available)
    use_stubs: bool = True          # T2 Flex: citations + permits
    use_stubs_reads: bool = True    # Genetec: plate reads
    use_stubs_payments: bool = True # T2 Iris: payments

    stub_data_dir: str = "../test-data"

    # Staff-uploaded plate reads land here; Genetec stub checks here first
    uploads_dir: str = "./uploads"

    excluded_permit_series: list[str] = ["BIKE"]


settings = Settings()
